travis:
  secure:
    BINSTAR_TOKEN: WRB9h4VJw+Ftx1xI+31pONM+BbSBOCriSKjlGMAisCnsSk4V4mcW+hT28f5Zt8noZBKtXn95VYl5XzoHbcSy8S+Fxp8vLCKtK1zqM5CAuFDQtrYyzoenCyEYxmuy2KaZqD+PRsk7EYxquWGEOzsgna+R1ztxbJU+vd+qfvWERG5BI3tPrbgWQohonmh9s0QXhWZjPLDdoqI4MQ5DbtMccMDwPHIjBd09Pd0gFrrwBqOcA4Tc2uYlul2AXqn3hicRV4Xb3YIEB8kfLMt2+2gZzrqcC5ViZXTxo5ph3888ipvBwDFH+LP69tzVmzJYrkuz1FVhyxRn/gZZKs0nmMoWkqxtJxWgc+FwycIQOAQ2ke96ASLcs3v7SAKB2wlFiwT9diILe69EvDoJ4Smm3cisPsIxMW1o+4IqAymT+vJ8hk73Vh4HVRLE30hCtI4ckNczlSURUzIuc5IvKncGMS0kFrCXwJ+Upc+LVe9e1N6UBsdBo21W/yPDWdjKTEsNFVfPBoXt3vBF6wT4aosw5npZ+ex+tDzlGszR2JkESlJTfvnvfq0c5K2q1aGqfHflJxoR4c6o2oc7Tprl7i8G4Gy+v+Kbbd/onnA11p8yLNORPcTk6MFXsJ+xHFORdmwIbTZsR4LQNW8/m/4D0rI8ivgwwbm2tyjdSdfnikETvH1ukwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
