travis:
  secure:
    BINSTAR_TOKEN: BqSBRtheZGMr/n7uY2qGMbtxbzZIC4pCx4eywzTa2hIXCgIr6zvU16qtEQSp6+IshTPWW4CTPRs9OU8mLng5fOFFYV1IUpn996G5aPqCShqnpwWCYI5RUv7iilSzovgnTx58ecoJVdqSISsijqZUBQaXh03RtReYJr6RKUeFhip1xC/aUOt4YminIaQeTl+pZESzzKEvfCf9DzzWkro7Ns3+nObH4tnZXT3NF0XNCY8rXmBaxpMfO+1XD/toJxnLNYPUAiB8RPJo+nSaw4DToCT2V0gj5S4Hevd+uEdPtRAQ9Zo22sH+2ECGv9eXorQbYBBSfsa+4SpcZONp+Ylf9zlGZBargblq5U7kbo1qUaa/nxOhTdfGiIV0ngkqe3oRW9JygNe9yEHaC5jnsBCfVUe9wkAL+2v6Adb60C2sbtOy2wPjEwOw06PPaAcmTu9hMh9/ScYKFSpzBIr8rCvB2bjiM3Alcmd+jMspBPIFV74O9UhSVTZkISq4w8Dikj4fzrW1y+Ps3SyuUlzP/12cmFWuXKZNWVR3Cp68XN2MLBFC4es6N+iHqHo6iP3dVsOINkU/s68wCzdlY6IFxVtLBBxcgPI0I1q5tvZaP/8bPVxCOJdGeOLgxNX+odyF6RYFG/UWKIbvaEIWgHiWjkkKVHThAGX/3LaRDQ5HQhyF0js=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
