travis:
  secure:
    BINSTAR_TOKEN: bElXwujh8APSoFfID1Uwr0hDXMVpaGN2PaKlG3oh/HdERMGhQqhAVSYg3vZVJ5FcbGpATh1QpHQKWZ9yVDo/kC87CVFkxnKIcOoGxtYgYEDU2Rjn7qiik49wM2iqSihSMYIYl0n79+UfZEThfAy/J0kDYwx2E0lTBvilDtq/WsjUqSqsVsYVrQwj4ewzTAplqnws1rYHVXF1gu9rWTMufJOF7f8hgXOuHd3EQJ6qRaMsy4IU4YnXVNFwX8U7qsZcH9ncfbmwGgTygotSQ6UMGfdq2eqwixA2o+Q6BYGCDKVD/7G8pRWxvDX8DK3P5mGnJJ4yNunmSu9tE+KwtOcjf5BW1vgQ75SSKj0Oi8YBkn+mjTacgb+zf9e1xuad/fuJOXKM/1KRKBNMAOXToq7J1FNWe8Jo2MsOgM4J9Qb4vSJ2ktwjP87sse1z/236e0WRrEDYqfZ6NbQy+mTOWDROQxgyelcZRQ5Vss014ZT5TbYrxzQ0iAEGNkQlIhIQEAywsmJDWB2HfZnqbOANlf/kG+/x8vtXuTnITAA+ECTx/i9zd50b5uMa/Md9x3yMj7/EVIuhkZFP8h4VBLCvu7yWYzblpJ+3bapUruHvrtN6KCgKrdvYmGyvwcpo2sC/liXFsaMWotRRdJRbQ7A2x46g8VnSROGgw27ibLjDwHOcwvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
